server:
  port: 8087
  servlet:
    context-path: /

spring:
  main:
    banner-mode: "off"
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    platform: h2
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:test;MODE=PostgreSQL
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://db4free.net:3306/examquiz?useSSL=false
    username: examquiz
    password: l0bzikas
  jpa:
#      hibernate.ddl-auto: create-drop
#      generate-ddl: true
#      show-sql: true

    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: create-drop
    show-sql: true
#    initialization-mode: always

  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select u.email, r.role from users u inner join user_role ur on(u.id=ur.user_id) inner join role r on(ur.role_id=r.role_id) where u.email=?


logging:
  level:
    org:
      springframework: ERROR